### ISSUE TITLE
Unable to detect iPad running iOS 13

### ISSUE THREAD

**Issue by Bilbosax** [hgoebl/mobile-detect.js#101]
I'm sorry, but I don't know where else to ask this question as I have been unable to find any solid reliable answers, but it does involve mobiledetect.js   I have a wordpress website marketing a mobile app that I have created.  When a user signs up for my service on my website, I want to redirect them to the correct app store based on the device they sign up on.  I have been using mobiledetect.js to do this, but as of iOS 13, I can no longer detect an iPad to send them to Apple's app store.  Could any one tell me whether this is a problem that mobiledetect is working on, or what other options I have to detect a modern iPad???

**Comment by hgoebl** [comment]
Hi, 

please search on the internet or ask on stackoverflow.
mobiledetect won't solve this problem. 

-Heinrich 

Am 12.01.2020 23:56, schrieb Bilbosax:

> I'm sorry, but I don't know where else to ask this question as I have been unable to find any solid reliable answers, but it does involve mobiledetect.js I have a wordpress website marketing a mobile app that I have created. When a user signs up for my service on my website, I want to redirect them to the correct app store based on the device they sign up on. I have been using mobiledetect.js to do this, but as of iOS 13, I can no longer detect an iPad to send them to Apple's app store. Could any one tell me whether this is a problem that mobiledetect is working on, or what other options I have to detect a modern iPad??? 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

  

Links:
------
[1]
https://github.com/hgoebl/mobile-detect.js/issues/101?email_source=notifications&amp;email_token=AAHWIQMYLELMIKTPJUPRIXDQ5ONYVA5CNFSM4KF2MH72YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IFTS72A
[2]

**Comment by skinandbones** [comment]
The test page confirms there's an issue detecting iPad running iOS 13.

https://hgoebl.github.io/mobile-detect.js/check/

<img width="1036" alt="Screen Shot 2020-02-04 at 4 35 11 PM" src="https://user-images.githubusercontent.com/16830/73789271-713bb580-476c-11ea-86a9-4096872b63a4.png">

**Comment by hgoebl** [comment]
Please ask Apple. They want the iPad to be detected as a desktop. Don't know why.

**Comment by MatthewPringle** [comment]
But there are still ways to detect the iPad as a device rather than desktop. Why not just alter the code to account for the changes Apple made?

**Comment by hgoebl** [comment]
Well implemented solutions in PRs are welcome.
