### ISSUE TITLE
Windows Phone detection

### ISSUE THREAD

**Issue by edriang** [hgoebl/mobile-detect.js#13]
Hi!, great script, but it doesn't work OK with Windows Phone.. I've uploaded an screencapture taken with my Windows Phone - Lumia 1020 running IE 11, OS version 8.1

As you can see, it says os is Android, mobile() returns iPhone, and also is('iPhone') and is('AndroidOS') returns true

It would be wonderful if you can fix this problem and let me now then

Thanks in advance for all your effort

![wp_ss_20141030_0001](https://cloud.githubusercontent.com/assets/2624002/4845964/a5796772-6048-11e4-85a4-a42e2a1d37b4.png)

**Comment by hooch** [comment]
Apparently the way to overcome this issue with IE11's desperation to please all comers, is to negate window.MSStream

    var iOS = /iPad|iPhone|iPod/.test(navigator.userAgent) && !window.MSStream;

https://stackoverflow.com/questions/9038625/detect-if-device-is-ios
