### ISSUE TITLE
Asus MemoPad FHD 10 Tablet

### ISSUE THREAD

**Issue by ruben82** [hgoebl/mobile-detect.js#14]
Thanks for sharing this util project.
I have a problem, Asus MemoPad FHD 10 Tablet is not recognized neither mobile device  or tablet or phone.
Could you tell me if I have to do something to make it works?

Thanks' in advance

R.

**Comment by serbanghita** [comment]
I've taken note of your request @ruben82 it will be fixed in the next version of `Mobile_Detect`

**Comment by hgoebl** [comment]
Thanks a lot! 

Am 07.01.2015 17:15, schrieb Serban Ghita: 

> I've taken note of your request @ruben82 [1] it will be fixed in the next version of Mobile_Detect 
> 
> --
> Reply to this email directly or view it on GitHub [2].

-- 

/*------------------------------------------------* 
 || heinrich goebl system programmierung
 || Rundsweg 1c
 || D-83026 Rosenheim
 || Tel.: 0 80 31 / 60 96 88
 || Mobil: +49 (0) 171 / 310.45.41
 || eMail: mailto:hgoebl@goebl.com
 || Web: http://www.goebl.com/
 *------------------------------------------------*/
 

Links:
------
[1] https://github.com/ruben82
[2]
https://github.com/hgoebl/mobile-detect.js/issues/14#issuecomment-69045182
