### ISSUE TITLE
Firefox OS is not detected correctly

### ISSUE THREAD

**Issue by digitarald** [hgoebl/mobile-detect.js#16]
Example UAs: https://developer.mozilla.org/en-US/docs/Web/HTTP/Gecko_user_agent_string_reference#Firefox_OS

Mobile: `Mozilla/5.0 (Mobile; rv:26.0) Gecko/26.0 Firefox/26.0`
Tablet: `Mozilla/5.0 (Tablet; rv:26.0) Gecko/26.0 Firefox/26.0`

It reports `tablet()` being `UnknownTablet` for the mobile UA.

**Comment by Goury** [comment]
So what?
The bug is still present.

**Comment by hgoebl** [comment]
I'm going to update to Mobile-Detect@2.8.12 asap (next weekend).

**Comment by Goury** [comment]
Thanks for status update!

**Comment by hgoebl** [comment]
For me it seems like there is no special way to detect Firefox *OS*.
For UA `Mozilla/5.0 (Mobile; rv:26.0) Gecko/26.0 Firefox/26.0` the mobile-detect.js demo page finds out:
![image](https://cloud.githubusercontent.com/assets/1008705/6676497/7fb88cce-cc28-11e4-87a4-2cad87692048.png)

What is wrong with it?
The new release of Mobile-Detect@2.8.12 won't bring any changes IMO.

@digitarald and @Goury: So what do you expect exactly (in sense of calling which method of the API of mobile-detect.js and the expected result)?

**Comment by Goury** [comment]
You can at least tell if its mobile or tablet by parsing "Mobile" string along with "Firefox" string.
Even UnknownPhone is better than None.

**Comment by hgoebl** [comment]
Once again: please tell me what exactly you expect. Example:

    var md = new MobileDetect('UA-String');
    expect(md.method('input')).toBe('expected-value');

I don't understand what you mean with 'tell if its mobile or tablet by parsing "Mobile" string along with "Firefox" string'.

**Comment by Goury** [comment]
I do expect
  var md = new MobileDetect('Mozilla/5.0 (Mobile; rv:26.0) Gecko/26.0 Firefox/26.0');
  md.phone();
to return
  "UnknownPhone"
instead of
  None

**Comment by hgoebl** [comment]
Thanks @Goury!
It turns out that this User-Agent string isn't detected at all, so it's a matter of screen size whether you get "UnknownPhone" or "UnknownTablet". Here is a [Plnkr](http://plnkr.co/edit/MMSUtmqXZbZ4vpg2BMS0?p=preview).

IMO the User-Agent string of FirefoxOS had to be more specific. I wouldn't know how to distinguish this from many others.
Does anybody have an idea which RegEx could identify FirefoxOS? Of course it should'nt be too greedy so that other RegEx don't have a chance to match (causing suffering for other devices).

**Comment by digitarald** [comment]
> IMO the User-Agent string of FirefoxOS had to be more specific. I wouldn't know how to distinguish this from many others.
If it has `Firefox` and `Mobile` but not `Android` it is Firefox OS.

**Comment by hgoebl** [comment]
@digitarald and how can this be expressed in a regular expression?
BTW why is Mozilla not a bit more concret about the OS?

**Comment by digitarald** [comment]
String matching would be the way to go vs fragile regular expressions that don't support inverse matching (for the does not include Android rule) and easily break in the future when the order of strings changes.

We choose a lean user agents and have rules to keep it lean [1] as UA detection is not a best practice. I assume you are expecting a string like `"FirefoxOS"` similar to `"Android"`?

[1]: https://wiki.mozilla.org/B2G/User_Agent/Device_Model_Inclusion_Requirements

**Comment by hgoebl** [comment]
Yes, I'd expect something like 'FirefoxOS'.

And yes, you're right: UA detection is not a best practice. But detecting an OS might be one of the things which cannot be realized easily with feature-detection and media queries.

One more thing: inverse matching would be a solution for now. But what if in 2016 Firefox is released for a new set-top box (think SmokeTV as a competitor of FireTV): not Android and not FirefoxOS. And now? With "not Android" it would be classified as "FirefoxOS".

**Comment by digitarald** [comment]
> With "not Android" it would be classified as "FirefoxOS".

Tablets and TVs don't have the `"Mobile"` bit, which is why substring matching has the best chance. What developers in this thread seem to depend on are `.phone()` and `.tablet()` to work correctly. How would this library help for TVs?

**Comment by hgoebl** [comment]
This library should help web applications to see where they run. This could be a TV as well.
Of course my example with TV is not good, but it should only show that "not rule => then concrete" may not be a good investment for future use.

The whole library works with regular expressions. There is not too much logic and besides the regexps are notoriously out-dated and not complete, it works more or less.

I've made a last change for Windows Phones (saying that they are iPhone, Android, Windows, Blackberry, all) but I'm not going to extend this spaghetti for more cases. It's already a nightmare to keep compatible with older versions (see issues).

**Comment by hgoebl** [comment]
If one day there is a possibillity to reliably detect FirefoxOS I'd fix this with pleasure.
