### ISSUE TITLE
Integration of detection logic Mobile-Detect@2.8.13 ?

### ISSUE THREAD

**Issue by knubew** [hgoebl/mobile-detect.js#28]
Thank you for updating the integration of detection logic to Mobile-Detect@2.8.13

I just have a short question. Do you use the current Version "Detect Mobile Browsers" (http://detectmobilebrowsers.com/) for integration which was released at 1 August 2014?

**Comment by hgoebl** [comment]
The patterns were not up-to-date. I've updated them. Difference: the new patterns recognize 'windows phone' as a mobile device.
I'm waiting for a possible bug in Mobile-Detect patterns regarding Windows Phone OS detection before building the next version.

**Comment by knubew** [comment]
Thanks for updating the "Detect Mobile Browsers" patterns.

Is there any reason why you did not add "|android|ipad|playbook|silk" to the first regex?

Under http://detectmobilebrowsers.com/about the author states:

Tablets
Android tablets, iPads, Kindle Fires and PlayBooks are not detected by design. To add support for tablets, add |android|ipad|playbook|silk to the first regex.tablets.

**Comment by hgoebl** [comment]
Yet another valuable input, thanks!
I'm thinking about either

a) add this pattern to the first regex, or
b) add another pattern to distinguish between "generic-phone/mobile" and "generic-tablet". Of course it's would only improve detection heuristic a bit, but maybe better than nothing. 

What do you think is better?

**Comment by knubew** [comment]
phuuu, good question. I use version a) for nearly two years now and it works good and it's proven. But maybe version b) might be the better way for upcoming devices in the future !? - At least it's up to you, sorry.
