### ISSUE TITLE
"UnknownPhome" under Opera Mini

### ISSUE THREAD

**Issue by knubew** [hgoebl/mobile-detect.js#29]
My "Samsung S2 (GT-I9100) is detected as "UnknownPhone" under "Opera Mini 7.6.40234" and "Opera Mini (New) 8.0.1807.91281". It seems that mobile-detect.js cannot identify the userAgent.

The fallback to the regex of detectmobilebrowsers.com seems to work, because it throws "UnknownPhone". Now I use the following working code:

    var md = new MobileDetect(window.navigator.userAgent);
    if (md.mobile() || md.mobile()=="UnknownPhone" || md.mobile()=="UnknownMobile" || md.mobile()=="UnknownTablet") {
    	// If a mobile or an unknown device (mobile, tablet, mobile) with not more than 600px is detected, switch to mobile site version
    	location.href = "https://m.xyz.com/";

**Comment by hgoebl** [comment]
This phone should be detected when not using Opera Mini. Please tell me the user-agent string when opening http://hgoebl.github.io/mobile-detect.js/check/ with your Opera Mini.

**Comment by knubew** [comment]
The user-agent string is:
Opera/9.80 (Android; Opera Mini/7.6.40234/36.2084; U; de) Presto/2.12.423 Version/12.16

The whole site conten was:

Mobile-Detect Check
(v1.0.0)
This is a small demo to check how mobile-
detect.js behaves with your mobile browser. You
can change the User-Agent to a complete other
one so you can see how that browser would be
detected. Keep in mind that in case of doubt
(phone or tablet) the smaller side of the screen
will be used to distinguish both device classes.
Input
User-Agent:
maxPhoneWidth (-1 to disable)
Result:
phone()
UnknownPhone
tablet()
-
mobile()
UnknownPhone
os()
AndroidOS
userAgent()
Opera
mobileGrade()
A
smaller side
300
is("AndroidOS")
true
is("Opera")
true
versionStr("Version")
"12.16"
version("Version")
12.16
versionStr("Opera")
"7.6.40234"
version("Opera")
7.640234
versionStr("Opera Mini")
"7.6.40234"
version("Opera Mini")
7.640234
versionStr("Opera Mobi")
"12.16"
version("Opera Mobi")
12.16
versionStr("Safari")
"12.16"
version("Safari")
12.16
versionStr("Presto")
"2.12.423"
version("Presto")
2.12423
versionStr("BlackBerry")
"12.16"
version("BlackBerry")
12.16

**Comment by hgoebl** [comment]
This is a problem of Opera Mini. It doesn't expose the device specific information (in this case GT-I9100) so. At least former versions of Firefox for Android had the same problem. I suppose when using Android stock browser or Chrome, it should be detected as Samsung Phone. AFAIK this problem cannot be solved.

**Comment by knubew** [comment]
Ok, but it was fixed with the new version 1.2.0 and the extend fallback pattern for unknown tablets (http://detectmobilebrowsers.com/). Thanks a lot.
