### ISSUE TITLE
Phablet category

### ISSUE THREAD

**Issue by asavin** [hgoebl/mobile-detect.js#30]
This is not an issue but a feature proposal - it would be much appreciated to get extra category for phablets, which are currently detected as phones.

**Comment by hgoebl** [comment]
Do you use mobile-detect server side or client side?

**Comment by nehaghai12** [comment]
I use mobile-detect as server side. is there any update if we can have one more category for Phablet devices ?

**Comment by hgoebl** [comment]
mobile-detect is just a parasite using the patterns of [Mobile-Detect](https://github.com/serbanghita/Mobile-Detect). Mobile-Detect only supports phone and tablet.

IMO it's really much work to split all phones and tablet into 3 categories. But you can ask there.

Another possibility would be to include a small JavaScript snippet which sneaks on the display size and pixel density and posts this information to your server-side session. Something like that...
