### ISSUE TITLE
Support for LG G3 phones

### ISSUE THREAD

**Issue by shmilky** [hgoebl/mobile-detect.js#32]
Can't recognize LG G3 different devices.
I encountered the issue on the LG G3 D855 but I can also see that there are devices of types:
D850 D851 D724 D690

I found the following link http://www.webapps-online.com/online-tools/user-agent-strings/dv/brand574739/lg-g3

For the LG G4 I read somewhere that it supposed to be H810 but again I didn't investigate it thoroughly.

**Comment by hgoebl** [comment]
Thanks for the precise information. As this project doesn't maintain user-agent strings, you should open an issue in the "mother-project" [Mobile-Detect](https://github.com/serbanghita/Mobile-Detect), that would be very kind.
