### ISSUE TITLE
Lenovo TAB 2 support

### ISSUE THREAD

**Issue by freemmy** [hgoebl/mobile-detect.js#35]
My Lenovo TAB 2 is detected as desktop. My device name in User Agent is "Lenovo TAB 2 A10-70L"

**Comment by serbanghita** [comment]
Thanks for the notice, I will add that to the next minor release of `Mobile_Detect`

**Comment by hgoebl** [comment]
mobile-detect is just a kind of "satellite"-project. It uses the RegEx patterns of
[Mobile-Detect](https://github.com/serbanghita/Mobile-Detect) and generates JavaScript source code
based on the code of its "mother"-project.

Missing patterns for particular devices cannot be added in mobile-detect.js,
instead you have to create an issue in [Mobile-Detect](https://github.com/serbanghita/Mobile-Detect).

Please provide the User-Agent string, the manufacturer and the type of device (phone, tablet, tv, bot, ...).

It doesn't make any sense to change generated code. I hope you understand.
