### ISSUE TITLE
ucbrowser detect as safari on android os

### ISSUE THREAD

**Issue by yinlianwei** [hgoebl/mobile-detect.js#36]

**Comment by hgoebl** [comment]
@yinlianwei could you please provide at least the UserAgent-string of your browser and if possible a code snippet how you test it?

**Comment by yinlianwei** [comment]
```var md = new MobileDetect(window.navigator.userAgent);
            alert(window.navigator.userAgent)
            alert(md.os());
            alert(md.userAgent());```

the out put:
`Mozilla/5.0 (Linux; U; Android 4.1.2; zh-CN; HUAWEI C8815 Build/HuaweiC8815) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/10.7.0.634 U3/0.8.0 Mobile Safari/534.30`
`AndroidOS`
`Safari`

my ucbrowser version V10.7.0.634 Android

**Comment by hgoebl** [comment]
That's a general problem. There is always a (unsorted) map of regular expressions and the first match exits with the result. In your case, the browser fakes to be Mobile Safari.

I've opened an issue serbanghita/Mobile-Detect#451 which could mitigate this, but then you'd have to call `md.is('UC Browser')` and would again not have 'UCBrowser' as result of calling `md.userAgent()`.

If you want, you can overwrite part of the implementation of `MobileDetect`. Look for examples in the test cases.

**Comment by yinlianwei** [comment]
OK! thanks.
