### ISSUE TITLE
Motorola G 2nd generation detection

### ISSUE THREAD

**Issue by Wouter33** [hgoebl/mobile-detect.js#37]
The Motorola G 2nd generation is detected as tablet, but it is a phone. Could you add it to the phones list?

User agent is: 

```
Mozilla/5.0 (Linux; Android 5.0.2; XT1068 Build/LXB22.46-28.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.94 Mobile Safari/537.36
```

Thanks!

**Comment by hgoebl** [comment]
Thanks @Wouter33 
I hope @serbanghita will take this quite often used smartphone into the list of Mobile-Detect project.

**Comment by hgoebl** [comment]
mobile-detect is just a kind of "satellite"-project. It uses the RegEx patterns of
[Mobile-Detect](https://github.com/serbanghita/Mobile-Detect) and generates JavaScript source code
based on the code of its "mother"-project.

Missing patterns for particular devices cannot be added in mobile-detect.js,
instead you have to create an issue in [Mobile-Detect](https://github.com/serbanghita/Mobile-Detect).

Please provide the User-Agent string, the manufacturer and the type of device (phone, tablet, tv, bot, ...).

It doesn't make any sense to change generated code. I hope you understand.
