### ISSUE TITLE
Android User Agent not recognized

### ISSUE THREAD

**Issue by peanut-lord** [hgoebl/mobile-detect.js#39]
Hello,

the following two user agent strings are both not detected by library (first one seems to be a web view from android)
- Mozilla/5.0 (Linux; Android 5.1.1; E5823 Build/32.0.A.4.11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Mobile Safari/537.36
- Mozilla/5.0 (Android 5.1.1; Mobile; rv:41.0) Gecko/41.0 Firefox/41.0

Thank you

**Comment by hgoebl** [comment]
Thanks. Can you tell me the phone types? (Vendor, Model)

**Comment by peanut-lord** [comment]
We don't know all the types, since we pulled those user agents from our log files, but it seems to be a problem with Sony Xperia Z3 and Z5.

**Comment by hgoebl** [comment]
Sorry, without concrete information I can't do anything.
@serbanghita, how do you process in such cases?
@peanut-lord, the source for the regexs for device detection are in https://github.com/serbanghita/Mobile-Detect

**Comment by peanut-lord** [comment]
The PHP library detect's those string correctl, we get a true for isMobile()

**Comment by hgoebl** [comment]
The js library detects this device as UnknownTablet or UnknownPhone, depending on screen size. Server-side (without screen size) it is detected as UnknownMobile (`mobile() is truthy`).

@serbanghita the new Sony Z5 Compact (E5803, E5823) is missing in the phone-section:

http://developer.sonymobile.com/downloads/whitepapers/xperia-z5-compact-e5803-and-e5823-white-paper/

This device has a relatively large market share (when looking at Sony, not compared to some Samsung devices).

**Comment by hgoebl** [comment]
mobile-detect is just a kind of "satellite"-project. It uses the RegEx patterns of
[Mobile-Detect](https://github.com/serbanghita/Mobile-Detect) and generates JavaScript source code
based on the code of its "mother"-project.

Missing patterns for particular devices cannot be added in mobile-detect.js,
instead you have to create an issue in [Mobile-Detect](https://github.com/serbanghita/Mobile-Detect).

Please provide the User-Agent string, the manufacturer and the type of device (phone, tablet, tv, bot, ...).

It doesn't make any sense to change generated code. I hope you understand.
