### ISSUE TITLE
Pale Moon desktop detected as phone

### ISSUE THREAD

**Issue by wolfbeast** [hgoebl/mobile-detect.js#40]
Specifically, the presence of "Goanna/xx" in the UA in v26+ is detected as a Wiko Goa phone.

**Comment by hgoebl** [comment]
Could you please provide the significant parts of the User-Agent string of Pale Moon desktop?

**Comment by wolfbeast** [comment]
The UA will always have the slice Goanna/nn.nn in the UA, and normally also always PaleMoon/nn.nn

Details about the entire UA's structure can be found in this post: https://forum.palemoon.org/viewtopic.php?f=24&t=9077

**Comment by hgoebl** [comment]
@serbanghita the regex `...|GOA|...` in wiko phones matches `Goanna`. Could this be surrounded by `\b` so it doesn't match `Goanna`?

**Comment by hgoebl** [comment]
Goanna has its own version detection now.

**Comment by wolfbeast** [comment]
:+1:
