### ISSUE TITLE
Windows 10 / edge not detected

### ISSUE THREAD

**Issue by fdalbo** [hgoebl/mobile-detect.js#41]
Hello
Thanks for you library
I noticed that Windows 10 OS and edge are not detect by version 1.3.1

**Comment by hgoebl** [comment]
Could you please give me examples of UserAgent strings? Fortunately I don't have Windows 10 ;-)

**Comment by fdalbo** [comment]
Here are the user agents:

Same user agent for edge on desktop and tablet.

**Edge - Windows 10 Desktop:**
`
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240
`
**Edge - Windows 10 Surface ***:
`
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586
`
* I put the surface into tablet and non-tablet mode, results were the same

**IE 11**
Windows 10 Desktop: 
`Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko`
Windows 10 Surface:  
`Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko`

**Comment by davenaeder** [comment]
+1 for this. Just came across the same issue.

**Comment by hgoebl** [comment]
IE11 should be detected:

```
versionStr("IE")
"11.0"
version("IE")
11
versionStr("Trident")
"7.0"
version("Trident")
7
versionStr("Windows NT")
"10.0"
version("Windows NT")
10
```

Detecting devices with Microsoft User-Agent strings usually is a hard job, because often they give not enough hints about the device or they are even misleading (telling they're an iPhone and Android).

And `mobile-detect.js` has it's focus on detecting mobile devices, not browsers.

Maybe @serbanghita could add support for detecting Microsoft Edge browser? I believe this could be helpful on Windows Phone, because it is sayed that it doesn't behave like IE.

**Comment by yikuo123** [comment]
I have found the same issue

![492357554af137a8c9c4d2b598d55172](https://cloud.githubusercontent.com/assets/13978174/18077094/a3b24b52-6eb5-11e6-8b49-d809d7b3e869.png)

**Comment by hgoebl** [comment]
@yikuo123 please repeat detection with following link and attach the output:

http://hgoebl.github.io/mobile-detect.js/check/

**Comment by yikuo123** [comment]
@hgoebl 

The link http://hgoebl.github.io/mobile-detect.js/check/ can not work with Microsoft Edge (PC and phone), the result as below:
![1](https://cloud.githubusercontent.com/assets/13978174/18115935/185a1c1c-6f76-11e6-9e39-1c1af5a39f0c.png)


Then I open it in IE 11 and input the User-Agent manually, the result as below:

Desktop User-Agent: 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393
Result:
phone()  - tablet()  - mobile()  - os()  - userAgent()  - mobileGrade()  A smaller side  1080 _version  1.3.3 2016-07-31 is("WebKit")  true versionStr("Chrome")  "51.0.2704.79" version("Chrome")  51.0270479 versionStr("Edge")  "14.14393" version("Edge")  14.14393 versionStr("Safari")  "537.36" version("Safari")  537.36 versionStr("Webkit")  "537.36" version("Webkit")  537.36 versionStr("Windows NT")  "10.0" version("Windows NT")  10  

Phone User-Agent:
Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; Microsoft; Lumia 650) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Mobile Safari/537.36 Edge/14.14263
Result:
phone()  NokiaLumia tablet()  - mobile()  NokiaLumia os()  WindowsPhoneOS userAgent()  Chrome mobileGrade()  A smaller side  1080 _version  1.3.3 2016-07-31 is("NokiaLumia")  true is("WindowsPhoneOS")  true is("Chrome")  true is("Edge")  true is("WebKit")  true versionStr("Chrome")  "46.0.2486.0" version("Chrome")  46.02486 versionStr("Edge")  "14.14263" version("Edge")  14.14263 versionStr("Safari")  "537.36" version("Safari")  537.36 versionStr("Webkit")  "537.36" version("Webkit")  537.36 versionStr("Android")  "4.2.1" version("Android")  4.21 versionStr("Windows Phone OS")  "10.0" version("Windows Phone OS")  10 versionStr("Windows Phone")  "10.0" version("Windows Phone")  10

**Comment by hgoebl** [comment]
OK, looks good to me. Where is the problem? Which function should return different values?

**Comment by hgoebl** [comment]
I close this.

* Edge is detected now (>= v1.3.4).
* Microsoft doesn't give enough hints about the device. Can't do anything here. Must be implemented by some heuristic algorithm by the consumer of this library. Note: "Touch" doesn't always mean mobile device. There are desktop systems with touch as well.

**Comment by DavidPhilip** [comment]
I still have this issue with `1.4.3` and the UA string of **Edge 18.17763** (`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763`). Can someone confirm this?

**Comment by hgoebl** [comment]
@DavidPhilip could you please explain:

- what value would you expect for which property?
- what wrong/unexpected value do you get?

The small online tool uses an outdated library, but I suppose you're using the current version.
