### ISSUE TITLE
Wrong version number in in the version dated 2015-12-28

### ISSUE THREAD

**Issue by knubew** [hgoebl/mobile-detect.js#42]
I think the version number in the version dated 2015-12-28 has to be 1.3.1, but in the file "mobile-detect.min.js" the version is "mobile-detect - v1.3.0 - 2015-12-28".

**Comment by hgoebl** [comment]
Thanks. I'll generating a new version as soon as Mobile-Detect bumps its version.

**Comment by serbanghita** [comment]
I've updated some regexes today. New devices (tablets).
