### ISSUE TITLE
How reliable would the detection be for just check if the device is a smartphone or tablet?

### ISSUE THREAD

**Issue by vtfn** [hgoebl/mobile-detect.js#43]
The README has a clear warning about the reliability of this kind of detection, ok. But if all I need is just check for mobile (smartphone and tablets), would it still have this reliability issue?

**Comment by serbanghita** [comment]
Yes @vtfn, that is because everyday new devices appear and it's hard to add them real-time to the detection class and some of them don't even provide a decent User-Agent or HTTP headers so we can make the differentiation.

**Comment by hgoebl** [comment]
@vtfn it's like @serbanghita says. If you need only very coarse detection, you could use

http://detectmobilebrowsers.com/

`mobile-detect.js` has the patterns of this small utility under the hood as a fallback.
