### ISSUE TITLE
Incorrect Typescript typings

### ISSUE THREAD

**Issue by mgroenhoff** [hgoebl/mobile-detect.js#46]
In order to import the constructor in Typescript with the new typings you need have the following:
```ts
import {MobileDetect} from "mobile-detect";
```
But the source suggests that you need to import it using:
```ts
import * as MobileDetect from "mobile-detect";
```
or
```ts
import MobileDetect = require("mobile-detect");
```

**Comment by hgoebl** [comment]
Could you please tell me where you found the suggestions how to import it?
Maybe you have **something concrete I should change in source or documentation.**
Is it working? Does TypeScript compiler output warnings? What kind of project do have (Node/Browser)?
For me it's not clear what to do...

**Comment by mgroenhoff** [comment]
Assigning to `exports` is incompatible with the way Typescript generates declaration files when exporting classes (which currently is the method that is used).

See the [handbook](https://www.typescriptlang.org/docs/handbook/modules.html) section **export = and import = require()**.

**Comment by hgoebl** [comment]
Many thanks for contributing @mgroenhoff :+1:

**Comment by serbanghita** [comment]
🍻
