### ISSUE TITLE
Does not work 

### ISSUE THREAD

**Issue by LeoIannacone** [hgoebl/mobile-detect.js#52]
With recent changes:
 * mobile() does not recognize tablets
 * phone() does not work with iPhone

**Comment by hgoebl** [comment]
please give me more information about the problem (environment browser/node, tested user agent, code snippets, return values/exceptions, ...)

**Comment by LeoIannacone** [comment]
Sorry, I think I had some misconfiguration. After reopening the browser I got it working correctly.

Thanks!
