### ISSUE TITLE
Samsung Galaxy Tab 10.1 not recognized as tablet

### ISSUE THREAD

**Issue by wilkerfoureaux** [hgoebl/mobile-detect.js#53]
Testing in browserstack I got this results:

https://snag.gy/tMKa0J.jpg

**Comment by hgoebl** [comment]
@wilkerfoureaux please tell me the User-Agent string for this device.

**Comment by wilkerfoureaux** [comment]
@hgoebl , this is showed in chrome browser of device `Mozilla/5.0 (Linux; Android 4.4.2; SM-T530 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.85 Safari/537.36`"
In native browser `Mozilla/5.0 (Linux; Android 4.4.2; en-us; SAMSUNG SM-T530 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/1.5 Chrome/28.0.1500.94 Safari/537.36`

**Comment by hgoebl** [comment]
Has to be fixed in source project Mobile-Detect

**Comment by hgoebl** [comment]
mobile-detect is just a kind of "satellite"-project. It uses the RegEx patterns of
[Mobile-Detect](https://github.com/serbanghita/Mobile-Detect) and generates JavaScript source code
based on the code of its "mother"-project.

Missing patterns for particular devices cannot be added in mobile-detect.js,
instead you have to create an issue in [Mobile-Detect](https://github.com/serbanghita/Mobile-Detect).

Please provide the User-Agent string, the manufacturer and the type of device (phone, tablet, tv, bot, ...).

It doesn't make any sense to change generated code. I hope you understand.
