### ISSUE TITLE
Add to the phone list: Huawei, Meizu, Xiaomi

### ISSUE THREAD

**Issue by vincefliek** [hgoebl/mobile-detect.js#54]
Hi! Thanks for this great lib. Is it possible to add to the phone list Huawei, Meizu and Xiaomi? These brands become more and more popular. FYI, during my tests on Huawei Honor 3C H30-U10 I had been receiving next values from methods:
1) mobile() returns 'UnknownMobile'
2) phone() returns null

**Comment by hgoebl** [comment]
1. we can do nothing without the User-Agent of these devices
2. it's better to create these kind of issues in the "mother-project": [Mobile-Detect](https://github.com/serbanghita/Mobile-Detect)

Thanks for contributing!
