### ISSUE TITLE
Add viewport meta for mobile readability

### ISSUE THREAD

**Issue by thevangelist** [hgoebl/mobile-detect.js#57]
Add <meta name="viewport" content="width=device-width, initial-scale=1"> to improve the readability on mobile devices.

## Without

![screen shot 2017-01-28 at 15 28 14](https://cloud.githubusercontent.com/assets/3482617/22396979/6c7391d4-e56e-11e6-8f4b-ab0b9a8534c4.png)

## With

![screen shot 2017-01-28 at 15 27 46](https://cloud.githubusercontent.com/assets/3482617/22396977/56cbf4d4-e56e-11e6-8488-2c1a50814335.png)

**Comment by hgoebl** [comment]
Is not part of this project.
