### ISSUE TITLE
Some useragents from browserstack could not be recognized

### ISSUE THREAD

**Issue by jonasemde** [hgoebl/mobile-detect.js#59]
Example Screenshot:
![Screenshot](https://cloud.githubusercontent.com/assets/5083193/24955750/07d6de92-1f85-11e7-8e31-8b55ea349073.png)

Some more user agents:
`Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; rv:11.0) like Gecko`
`Mozilla/5.0 (MSIE 10.0; Windows NT 6.1; Trident/5.0)`
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36`

**Comment by hgoebl** [comment]
Has to be fixed in source project Mobile-Detect

**Comment by hgoebl** [comment]
mobile-detect is just a kind of "satellite"-project. It uses the RegEx patterns of
[Mobile-Detect](https://github.com/serbanghita/Mobile-Detect) and generates JavaScript source code
based on the code of its "mother"-project.

Missing patterns for particular devices cannot be added in mobile-detect.js,
instead you have to create an issue in [Mobile-Detect](https://github.com/serbanghita/Mobile-Detect).

Please provide the User-Agent string, the manufacturer and the type of device (phone, tablet, tv, bot, ...).

It doesn't make any sense to change generated code. I hope you understand.
