### ISSUE TITLE
Unknown Environment - Google Big Query

### ISSUE THREAD

**Issue by dsouzarc** [hgoebl/mobile-detect.js#60]
I tried using this library as part of a UDF script in Google BigQuery and got the "Error: unknown environment" log message at like 990 (mobile-detect.js) and saw that the comment on the line above said that I should file a bug report when I got that error.

How can I help fix this issue?

**Comment by hgoebl** [comment]
How and where do you use it? I cannot imagine what's the use-case in BigQuery...

**Comment by dsouzarc** [comment]
BigQuery allows you to use JavaScript while querying the database for additional code execution/query refinement (the benefit is that this processing is also done on Google's servers). 

If I have a column for userAgents, I can use JavaScript and BigQuery to parse the UserAgent and modify the table returned with information about that userAgent (i.e.: whether or not the userAgent is for a mobile or tablet device).

```
function parse_useragent(useragent) {
    var md = new MobileDetect(useragent)
    return md.is('iPhone')
}
```
Or something like that (essentially)

**Comment by hgoebl** [comment]
Is there a "BigQuery in 5 minutes" tutorial where I can do some testing/debugging? Do I need an account for that?
Or could you debug the few lines around "unknown environment"?

**Comment by dsouzarc** [comment]
You don't need an account for it. There are some publicly hosted datasets that you can run queries on [here](https://cloud.google.com/bigquery/public-data/) but none of them seem to have UserAgent IDs. 

What do the lines around "unknown environment" do? Or what am I looking for specifically? 

Thank you for your help

**Comment by hgoebl** [comment]
sorry, have to close this. Not enough consumers of the lib are interested in this.
