### ISSUE TITLE
cant detect android 5 and anroid 6 versions

### ISSUE THREAD

**Issue by fsarihan** [hgoebl/mobile-detect.js#61]
cant detect android 5 and anroid 6 versions

**Comment by hgoebl** [comment]
please provide user-agent string

**Comment by jmalkan** [comment]
I am also experiencing similar issues on android 6/7 on samsung devices.
On samsung Galaxy S5, fails to detect if I use FireFox but detects correctly if I use Chrome. Please see below the user-agent string

Mozilla/5.0 (Android 6.0.1; Mobile; rv:54.0) Gecko/54.0 Firefox/54.0
Mozilla/5.0 (Linux; Android 6.0.1; SM-G900H Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36

Doesn't work on Samsung Galaxy Note 4 - below the user-agent string
Mozilla/5.0 (Linux; Android 6.0.1; SM-N910T Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36

Doesn't work on Samsung Galaxy S6 Edge - below the user-agent string
Mozilla/5.0 (Linux; Android 7.0; SM-G925T Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36

**Comment by nikunjdnp** [comment]
I am also experiencing similar issues on android 7 on Redmi devices. getting response is **UnknownMobile**.

**Comment by hgoebl** [comment]
mobile-detect is just a kind of "satellite"-project. It uses the RegEx patterns of
[Mobile-Detect](https://github.com/serbanghita/Mobile-Detect) and generates JavaScript source code
based on the code of its "mother"-project.

Missing patterns for particular devices cannot be added in mobile-detect.js,
instead you have to create an issue in [Mobile-Detect](https://github.com/serbanghita/Mobile-Detect).

Please provide the User-Agent string, the manufacturer and the type of device (phone, tablet, tv, bot, ...).

It doesn't make any sense to change generated code. I hope you understand.
