### ISSUE TITLE
Errors on @types/mobile-detect

### ISSUE THREAD

**Issue by ElliDy** [hgoebl/mobile-detect.js#62]
When trying to compile a ts file, which imports mobile-detect, the following errors appear:

mobile-detect.d.ts(70,1): Error TS1128: Declaration or statement expected.
mobile-detect.d.ts(70,11): Error TS1005: ';' expected.
mobile-detect.d.ts(70,33): Error TS1005: '{' expected.

Would be nice, if this can be solved in nearly future.

**Comment by hgoebl** [comment]
Could you please provide a slim setup to reproduce the bug?
BTW `@types/mobile-detect` is not maintained by me. There is a `.d.ts` file in the node module of `mobile-detect.js`.

**Comment by hgoebl** [comment]
Closing this issue as it's unclear whether problem still exists and no answer coming from @ElliDy
