### ISSUE TITLE
How to detect table iPad Pro?

### ISSUE THREAD

**Issue by tronghiep92** [hgoebl/mobile-detect.js#69]
Hi guys,

Sometimes, I just want to detect only iPad Pro without IPad.
Or somehow I want to it looks like this:
```js
if(md.table() && width >= 1024) {
  // do stuff
} 
```
Because I'm using `mobile-detect.js` in Node.js environment so I cannot get width device by `screen.width/height`

Thanks, advance.

**Comment by hgoebl** [comment]
Not possible server side.
