### ISSUE TITLE
What about moving constants to a separate file?

### ISSUE THREAD

**Issue by toubou91** [hgoebl/mobile-detect.js#72]
Hello,

nice effort.

However, I think it would be much cleaner if we kept constants like [`phone`](https://github.com/hgoebl/mobile-detect.js/blob/master/mobile-detect.js#L13), [`tablets`](https://github.com/hgoebl/mobile-detect.js/blob/master/mobile-detect.js#L13), etc. in an isolated file, like the way it's done for [math.js](https://github.com/toubou91/math.js/blob/master/lib/constants.js) or [international-anniversary](https://github.com/anniversaries/international-anniversary/blob/master/anniversaries.js).

How does this sound to you?

Cheers,
Thodoris

**Comment by hgoebl** [comment]
Generally a good idea. But in this case, the js file is generated based on a template without the constants. So from a maintenance point of view, I think it's already ok if you look at the "real" source files.
And those guys who want to load the code into the browser are glad to have only a single request.
