### ISSUE TITLE
Is the library broken?

### ISSUE THREAD

**Issue by AvraamMavridis** [hgoebl/mobile-detect.js#73]
## Issue

Seems that many of the libraries functions returns `null`, even on the demo page:

<img width="538" alt="screen shot 2018-01-02 at 13 53 18" src="https://user-images.githubusercontent.com/283690/34484344-6efb41de-efc4-11e7-9ed9-b85e57cb50d0.png">

e.g. `md.userAgent()`

Is a bug on the library or is a change on Chrome/Firefox that broke it?

**Comment by hgoebl** [comment]
I really hope that it's not broken. And I also think that it's OK. Maybe the demo (not included in this project) is out-dated. Try this:

http://hgoebl.github.io/mobile-detect.js/check/

Please keep in mind that the library's target is "mobile", so when using desktop browsers, most features won't work as one might expect.

**Comment by AvraamMavridis** [comment]
> Please keep in mind that the library's target is "mobile", so when using desktop browsers, most features won't work as one might expect.

I see, probably that's the issue, I dont see the user agent on desktop. Thx.

**Comment by virtualbjorn** [comment]
Is it possible to extend its feature to desktop as well?

**Comment by hgoebl** [comment]
Probably not. There is not much contribution to this project and the "mother"-project written in PHP. It's kind of starving, I'm afraid.
