### ISSUE TITLE
How to detect standalone

### ISSUE THREAD

**Issue by bernatfortet** [hgoebl/mobile-detect.js#74]
I'm trying to find out whether a user in a mobile devices is in standalone mode. That is, when a user adds the website to their homescreen.

Thanks

**Comment by hgoebl** [comment]
see https://developers.google.com/web/updates/2015/10/display-mode

**Comment by bernatfortet** [comment]
hi @hgoebl it would be fantastic if your library were to unify the detection for all platforms. Thanks for the link anayway
