### ISSUE TITLE
Nexus_5X UnknownPhone in browser and null in nodejs. 

### ISSUE THREAD

**Issue by nghiepit** [hgoebl/mobile-detect.js#75]
HI guys,

I'm using `Android Emulator` build device `Nexus_5X_API_24`

My user-agent `Mozilla/5.0 (Linux; Android 7.0; Android SDK built for x86 Build/NYC) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.111 Mobile Safari/537.36`.

```js
md.phone() // UnknownPhone in browser and null in nodejs
```

Thank in advance.

**Comment by hgoebl** [comment]
@nghiepit you should not just remove the text and place an issue in the wrong project.
