### ISSUE TITLE
MobileDetect is not defined

### ISSUE THREAD

**Issue by knubew** [hgoebl/mobile-detect.js#84]
I'm using mobile-detect ("mobile-detect v1.4.2 2018-06-10") on several websites without any problems. But on one website I get the error "MobileDetect is not defined". 

I'm really NO expert for JavaScript and therefore I've googled a lot, but I did not find helpfull search results.

Does anyone have a tip for me or can help me, please?

**Comment by hgoebl** [comment]
Is the website reachable from outside?

**Comment by knubew** [comment]
Yes, it is.
Is it possible to send the URL in a private message to you?

**Comment by hgoebl** [comment]
yes, my email is in my profile.

**Comment by knubew** [comment]
Fine, First I will load up the not minified version of my caller script. Then it maybe more easy for you to find the reason for "MobileDetect is not defined".

**Comment by varadig** [comment]
Same issue here.
`ReferenceError: mobile is not defined`

Maybe you can share the solution?

**Comment by khurramwasim** [comment]
I am facing the same problem, I have mobile detect working fine on 2 magento websites, but on a wix website I get the error "Mobile detect is undefined."

**Comment by hgoebl** [comment]
@khurramwasim 100% sure that the problem is not on this libraries side. Ask on stackoverflow, provide your code and diagnostic data, e.g. the correct error message.
