### ISSUE TITLE
mobile-detect pixel size device change

### ISSUE THREAD

**Issue by Igor-Vuk** [hgoebl/mobile-detect.js#86]
This is more of a question then a problem. Can please somebody tell at what screen size will mobile-detect report tablet, mobile. For example, if width is below 320px it's mobile. I cannot find this information.

Thank you

**Comment by hgoebl** [comment]
http://hgoebl.github.io/mobile-detect.js/doc/MobileDetect.html

> maxPhoneWidth | number | <optional> | 600 | only for browsers specify a value for the maximum width of smallest device side (in logical "CSS" pixels) until a device detected as mobile will be handled as phone. This is only used in cases where the device cannot be classified as phone or tablet.See Declaring Tablet Layouts for Android.If you provide a value < 0, then this "fuzzy" check is disabled.
