### ISSUE TITLE
detect phone from sumsung galaxy j7 or Android OS return null

### ISSUE THREAD

**Issue by masato48** [hgoebl/mobile-detect.js#87]
**detect phone from sumsung galaxy j7 or Android OS return null**

**user-agent from sumsung galaxy j7 prime is**
Mozilla/5.0 (Linux; Android 7.0; SM-G610F Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.91 Mobile Safari/537.36

**but phone detect is null**
```
const md = new MobileDetect(req.headers['user-agent'])
console.log(md.mobile())
console.log(md.phone())
console.log(md.tablet())
```

**result**
```
UnknownMobile
null
null
```

I change to other Android Device 
result the same

**Comment by hgoebl** [comment]
Do you remember the text showing up when creating an issue?

I repeat:




## Important Note

**Before creating an issue**, please note:

mobile-detect is just a kind of "satellite"-project. It uses the RegEx patterns of
[Mobile-Detect](https://github.com/serbanghita/Mobile-Detect) and generates JavaScript source code
based on the code of its "mother"-project.

Missing patterns for particular devices cannot be added in mobile-detect.js,
instead you have to create an issue in [Mobile-Detect](https://github.com/serbanghita/Mobile-Detect).

Please provide the User-Agent string, the manufacturer and the type of device (phone, tablet, tv, bot, ...).

I won't replicate your issue to Mobile-Detect!

It doesn't make any sense to change generated code. I hope you understand.



## Issue

[ ] I've read above note and I'm quite sure I have a real issue with mobile-detect.js



... you can delete above note and just describe your issue ...

**Comment by stevenalanstark** [comment]
You seem to be missing the point. Ipad will have the same user agent as
desktop, making it impossible to detect via user agents

**Comment by hgoebl** [comment]
`SM-G610F` should be added as a pattern in the Mobile-Detect project, not here.
