### ISSUE TITLE
Why build so strange?

### ISSUE THREAD

**Issue by unclechu** [hgoebl/mobile-detect.js#9]
How I can build mobile-detect without php and this files?:
path.join(__dirname, '..', '..', 'Mobile-Detect', 'tests', 'ualist.json')

Why you don't using just grunt (or gulp), without generate script?

**Comment by hgoebl** [comment]
Too much work to eliminate dependency to PHP.
Maybe some day I provide Grunt or Gulp.js based scripts, but PHP will be necessary in all cases.
