### ISSUE TITLE
OnePlus 5 not detected as Phone

### ISSUE THREAD

**Issue by sirajulm** [hgoebl/mobile-detect.js#91]
Not deteccting `ONEPLUS 5` device as `phone`.
User Agent: `Mozilla/5.0 (Linux; Android 8.0.0; ONEPLUS A5000 Build/OPR6.170623.013) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.137 Mobile Safari/537.36`

**Comment by hgoebl** [comment]
as stated in the text when creating an issue, please open issues like that in Mobile-Detect PHP project.
