### ISSUE TITLE
请问一下调用这个函数的时候出现this.ua is not defined？有遇到过？

### ISSUE THREAD

**Issue by huxiulin** [hgoebl/mobile-detect.js#96]
## Important Note

**Before creating an issue**, please note:

mobile-detect is just a kind of "satellite"-project. It uses the RegEx patterns of
[Mobile-Detect](https://github.com/serbanghita/Mobile-Detect) and generates JavaScript source code
based on the code of its "mother"-project.

Missing patterns for particular devices cannot be added in mobile-detect.js,
instead you have to create an issue in [Mobile-Detect](https://github.com/serbanghita/Mobile-Detect).

Please provide the User-Agent string, the manufacturer and the type of device (phone, tablet, tv, bot, ...).

I won't replicate your issue to Mobile-Detect!

It doesn't make any sense to change generated code. I hope you understand.

## Issue

[ ] I've read above note and I'm quite sure I have a real issue with mobile-detect.js

... you can delete above note and just describe your issue ...

**Comment by hgoebl** [comment]
Sorry, I don't understand.
